---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: flux-system-test
  namespace: flux-system-test
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system-test
  url: ssh://git@github.com/Hope3r/flux2-kustomize-helm-example
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system-test
  namespace: flux-system-test
spec:
  interval: 30s
  path: ./clusters/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system-test
  validation: client
