apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-charts
  namespace: chartmuseum
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: chartmuseum
  nfs:
    server: 192.168.1.24
    path: "/var/k8s/nginx"