apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chartmuseum
spec:
  releaseName: chartmuseum
  chart:
    spec:
      chart: chartmuseum
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
      version: "3.1.0"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    env:
      open:
        DISABLE_METRICS: false
        DISABLE_API: false
    serviceMonitor:
      enabled: true
      namespace: prometheus
    ingress:
      enabled: true
      hosts:
        - name: registry.local
          path: /
          tls: false
    persistence:
      enabled: true
      path: /storage
      storageClass: chartmuseum
      volumeName: nfs-charts
      pv:
        enabled: true
        pvname: nfs-charts
        capacity:
          storage: 8Gi
        accessMode: ReadWriteOnce
        nfs:
          server: 192.168.1.24
          path: "/var/k8s/nginx"