apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-nginx
resources:
  - ../../base/nginx
---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: github-nginx
patchesStrategicMerge:
  - nginx-values.yaml