apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  # namespace: github-nginx
spec:
  chart:
    spec:
      version: ">=0.1.1"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - oui.nginx.staging
