apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: helm-registry
  namespace: github-helm-registry
spec:
  chart:
    spec:
      version: ">=0.1.1"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - helm-registry.staging
