apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system-test
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system-test
  path: ./infrastructure
  prune: true
  validation: client
