apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: github-nginx
spec:
  chart:
    spec:
      version: ">=0.1.1"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - nginx.staging
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: github-podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - podinfo.staging
