apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: github-registry
spec:
  chart:
    spec:
      version: ">=0.1.1"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - registry.staging
    extraFiles:
      /usr/share/nginx/html/index.html: |-
        <h1>Test</h1>
