kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-artifact-hub-postgresql-0
  namespace: artifact-hub
  labels:
    app: postgresql
    release: artifact-hub
    role: master
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  storageClassName: artifact-hub