apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: artifact-hub
spec:
  releaseName: artifact-hub
  chart:
    spec:
      chart: artifact-hub
      sourceRef:
        kind: HelmRepository
        name: artifact-hub
        namespace: flux-system
      version: "0.20.0"
  interval: 30s
  install:
    remediation:
      retries: 3
  values:
    hub:
      server:
        allowPrivateRepositories: true
        basicAuth:
          enabled: true
          username: hub
          password: hub
      service:
        type: ClusterIP
        port: 80
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        rules:
        - host: hub.local
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                serviceName: hub
                servicePort: 80
        tls: []
    # trivy:
    #   persistence:
        