apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: github-registry
spec:
  chart:
    spec:
      version: ">=0.1.1"
  test:
    enable: false
  values:
    ingress:
      hosts:
        - registry.production
    ## Additional volumeMounts to the main container.
    extraVolumeMounts:
      - name: config
        mountPath: /usr/share/nginx/html/index.html
        subPath: index

    ## Additional volumes to the pod.
    # extraVolumes:
      # - name: volume
      #   emptyDir: {}

    ## Additional files to the configmap.
    extraFiles:
      index: |
        production