apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: registry
  namespace: github-registry
spec:
  releaseName: registry
  chart:
    spec:
      chart: nginx
      sourceRef:
        kind: HelmRepository
        name: chartmuseum
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  # Default values
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: "/"
